In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import neighbors, datasets, preprocessing
from sklearn.preprocessing import StandardScaler

data = datasets.load_iris()

In [2]:
def sigmoid(x):
    deno = 1 + np.exp(-x)
    return 1 / deno

def accuracy(y, y_predicted):
    acc = np.sum(y == y_predicted)
    acc /= len(y)
    return acc

class Logistic_Regression:
    
    def __init__(self, iterations, alpha): # iterations default 1000, alpha default 0.001
        self.alpha = alpha
        self.iterations = iterations
        self.thetas = None # thetas
        self.bias = 0
        
    def fit(self, X, y):
        points, num_features = X.shape

        # init parameters
        self.thetas = np.zeros(num_features)

        # gradient descent
        for i in range(self.iterations):
            # approximate y with linear combination of thetas and x, plus bias
            linear_combination = np.dot(X, self.thetas) 
            lin_reg_eq = linear_combination + self.bias
            # apply sigmoid function
            y_pred = sigmoid(lin_reg_eq)

            # compute gradients

            dn = np.dot(X.T, (y_pred - y))
            d0 = np.sum(y_pred - y)

            dw = dn / points
            db = d0 / points
            # update parameters
            self.thetas = self.thetas - dw * self.alpha
            self.bias = self.bias - db * self.alpha

    def predict(self, X):
        proj = np.dot(X, self.thetas)
        lin_reg_eq = proj + self.bias
        
        return np.array([i for i in sigmoid(lin_reg_eq)])

# class FDA:
#     def __init__(self):
#         self.eigenvectors = None
#         self.num_classes = 2
    
#     def process(self, data, labels):
#         cov_w = 0
#         height, width = data.shape
#         cov_t = np.cov(data.T)*(height-1)
        
#         uc = np.unique(labels)
#         n_unique = len(uc)
        
#         for i in range(0, n_unique):
#             cov_items = np.flatnonzero(uc[i] == labels)
#             cov_w += (len(cov_items)-1) * np.cov(data[cov_items].T)
        
#         cov_b = cov_t - cov_w
#         pinv_dot = np.linalg.pinv(cov_w).dot(cov_b)
#         dump, eigenvectors = np.linalg.eigh(pinv_dot)
        
#         # print(eigenvectors.shape)
        
#         principal = data.dot(eigenvectors[:,::-1][:,:self.num_classes])
        
#         # print(principal.shape)
        
#         if self.num_classes == 2:
#             if labels is not None:
#                 unique_labels = np.unique(labels)
#                 zip_dict = zip(['m', 'y', 'c'], unique_labels)
#                 for clr, lbl in zip_dict:
#                     flat_ids = np.flatnonzero(labels==lbl)
#                     c_data = principal[flat_ids]
#                     argX = c_data[:,0]
#                     argY = c_data[:,1]
#                     plt.scatter(argX, argY, c=clr)
#             else:
#                 plt.scatter(principal[:,0], principal[:,1])
#             plt.show()
        
#         return principal


In [3]:
X = data.data
y = data.target

scaler = StandardScaler()
scaler.fit(X)
X_normalised = scaler.transform(X)

print(X_normalised)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [17]:
logisticRegressor = Logistic_Regression(alpha=0.001, iterations=1000)

X_train, X_test, y_train, y_test = train_test_split(
    X_normalised, y, test_size=0.7, random_state=1
)

y_train_0 = (y_train == 0).astype(int)
y_train_1 = (y_train == 1).astype(int)
y_train_2 = (y_train == 2).astype(int)

logisticRegressor.fit(X_train, y_train_0)
predictions_0 = logisticRegressor.predict(X_test)

logisticRegressor.fit(X_train, y_train_1)
predictions_1 = logisticRegressor.predict(X_test)

logisticRegressor.fit(X_train, y_train_2)
predictions_2 = logisticRegressor.predict(X_test)

predictions = []

for i in range(predictions_0.shape[0]):
    tmp = [predictions_0[i], predictions_1[i], predictions_2[i]]
    predictions.append(tmp.index(max(tmp)))

predictions = np.array(predictions)
print(accuracy(y_test, predictions))
# 0.8762

0.8761904761904762


### Notes:
Does it provide better results than the ones reported in Q4? **No**.